### PR TITLE
DOC: add CoC committee

### PR DESCRIPTION
**Pull request by tacaswell**
As discussed on the 2022-06-30 call.

We plan to re-vamp this sub-committee in the next 9-12 months, but start with this list.

### CODE REVIEW

**Comment by tacaswell** [comment]
@jklymak Is this the same failure we had on the brochure site?

**Comment by jklymak** [comment]
Yes @QuLogic tracked it to having to pin pigments.

**Review by dopplershift — APPROVED** [review]

**Comment by jklymak** [comment]
Probably, until we release 3.6 and the website changes on dev, we should pin pydata-sphinx-theme to be <0.9.0

**Comment by efiring** [comment]
I tried rerunning the checks with the pinned pydata_sphinx_theme, but it fails with
```
Extension error (pydata_sphinx_theme):
Handler <function _overwrite_pygments_css at 0x7f8f5b3b6ca0> for event 'build-finished' threw an exception (exception: 'HtmlFormatter' object has no attribute 'get_linenos_style_defs')
make: *** [Makefile:32: html] Error 2
Error: Process completed with exit code 2.
```

**Comment by tacaswell** [comment]
rebased.

**Pull request merged**
